### ISSUE TITLE
t.equal spits some confusing errors

### ISSUE THREAD

**Issue by mixmix** [tbeseda/tap-spek#24]
```js
  t.equal(  // should have been deepEqual
    ['Foo'],
    ['Foo']
  )
```

get this error
![image](https://user-images.githubusercontent.com/2665886/159873626-4e443ae5-7e9b-4b84-ac5d-6cd4e62e43cb.png)

Which is very confusing / misleading

**Comment by tbeseda** [comment]
Hey @mixmix which tap generator are you using? It might be tape?
There's definitely a bug there, but it's hard to narrow in since I think we're running into issues with differing TAP output.
~~I've accounted for the cases you demonstrate here and in #25~~ narrowed it down, will release a patch today
I'd like to handle more types of TAP output.

**Comment by mixmix** [comment]
I'm using the latest tape. 
Andy are you using?
